controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

backoffice:
    path: /admin
    controller: App\Controller\BackofficeController::index

debug:
    path: /debug
    controller: App\Controller\DebugController::index

